"use client";

import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { BookOpen, BrainCircuit, Command, GitBranch, LayoutDashboard, Menu, Moon, Plus, Search, Settings, Sun, X } from "lucide-react";

const links=[[/dashboard/,"Dashboard",LayoutDashboard],[/design\/new/,"New Design",Plus],[/examples/,"Examples",BookOpen],[/interview/,"Interview Mode",BrainCircuit],[/settings/,"Settings",Settings]] as const;
export function AppShell({children}:{children:React.ReactNode}){
 const path=usePathname(); const [open,setOpen]=useState(false); const [dark,setDark]=useState(false); const [palette,setPalette]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("archai:theme");const next=saved? saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches;setDark(next);document.documentElement.dataset.theme=next?"dark":"light"},[]);
 function theme(){const next=!dark;setDark(next);localStorage.setItem("archai:theme",next?"dark":"light");document.documentElement.dataset.theme=next?"dark":"light"}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(v=>!v)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="n"){e.preventDefault();location.href="/design/new"}if(e.key==="Escape"){setPalette(false);setOpen(false)}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
 return <div className="min-h-screen bg-[var(--canvas)]"><button className="fixed left-3 top-3 z-40 grid size-11 place-items-center rounded-lg border border-[var(--border)] bg-[var(--canvas)] lg:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button>
 <aside className={`fixed inset-y-0 left-0 z-50 w-72 border-r border-[var(--border)] bg-[var(--surface)] p-4 transition-transform lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><div className="flex h-full flex-col"><div className="flex min-h-12 items-center justify-between px-2"><a href="/" className="flex items-center gap-2 font-semibold"><GitBranch className="text-[var(--accent)]"/>ArchAI</a><button onClick={()=>setOpen(false)} className="grid size-11 place-items-center lg:hidden" aria-label="Close navigation"><X/></button></div><nav className="mt-6 grid gap-1">{links.map(([href,label,Icon])=><a key={label} href={String(href).replaceAll("/","").includes("design")?"/design/new":String(href)} className={`flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-semibold ${path.match(href)?"bg-[var(--accent-soft)] text-[var(--accent)]":"text-[var(--muted)] hover:bg-[var(--canvas)]"}`}><Icon size={18}/>{label}</a>)}</nav><div className="mt-auto rounded-lg border border-[var(--border)] bg-[var(--canvas)] p-3 text-xs text-[var(--muted)]"><b className="text-[var(--text)]">Local-first</b><p className="mb-0">Designs stay in this browser. No account or database required.</p></div></div></aside>
 <div className="lg:pl-72"><header className="sticky top-0 z-30 flex min-h-16 items-center justify-end gap-2 border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--canvas)_92%,transparent)] px-5 backdrop-blur"><button onClick={()=>setPalette(true)} className="hidden min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-sm text-[var(--muted)] sm:flex"><Search size={16}/>Search designs <kbd>⌘K</kbd></button><button onClick={theme} className="grid size-11 place-items-center rounded-lg border border-[var(--border)]" aria-label="Toggle theme">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><a href="/design/new" className="flex min-h-11 items-center gap-2 rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-white"><Plus size={17}/>New Design</a></header>{children}</div>
 {palette&&<div className="fixed inset-0 z-[70] grid place-items-start bg-black/35 p-4 pt-[12vh]" onMouseDown={()=>setPalette(false)}><div className="mx-auto w-full max-w-xl rounded-xl border border-[var(--border)] bg-[var(--canvas)] p-3 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-[var(--border)] px-3 pb-3"><Command size={18}/><input autoFocus placeholder="Search designs or run a command…" className="min-h-11 flex-1 bg-transparent outline-none"/></div><div className="grid gap-1 pt-2">{links.map(([href,label,Icon])=><a key={label} href={String(href).replaceAll("/","").includes("design")?"/design/new":String(href)} className="flex min-h-11 items-center gap-3 rounded-lg px-3 hover:bg-[var(--surface)]"><Icon size={17}/>{label}</a>)}</div></div></div>}</div>
}
